### ISSUE TITLE
Possible to retrieve GPR string from reaction object?

### ISSUE THREAD

**Issue by willigott** [SystemsBioinformatics/cbmpy#13]
Is there a straightforward way to retrieve the GPR string directly from the reaction object, so something along the lines
```
r = model.getReaction(rea_id)
gpr_str = r.getAssociationString()
```
?

I see currently two ways of accomplishing it

1) via the model object itself:

`gpr_str = model.getGPRforReaction(rea_id).getAssociationStr()`

2) via the reaction object which is rather complicated:

`r.__objref__().getGPRforReaction(r.getId()).getAssociationStr()`

I think it would be nice to have 2) available on the reaction object as a built-in function e.g. `getGPRstring()`.

Would this be possible?

**Comment by bgoli** [comment]
getGPRassociationString() added to reaction object

**Comment by willigott** [comment]
Great, thanks! 

I think the `out = None` in the `except` is not necessary as you initialized `out` before the `try / except`.
