### ISSUE TITLE
Failed with sympy 1.8

### ISSUE THREAD

**Issue by lptolik** [SystemsBioinformatics/cbmpy#36]
sympy 1.8 satisfy requirements in environment.yml, but the code in CBLPK.py
```
    if (
        int(sympy.__version__.split('.')[1]) >= 7
        and int(sympy.__version__.split('.')[2]) >= 4
    ):
        HAVE_SYMPY = True
```
fails as there is no third version and it would fail till 1.8.4.

**Comment by bgoli** [comment]
Thanks, this should be fixed in 0.8.1 please upgrade CBMPy and try again.
